//runtime error

const runtimeError = () => {
    console.log(a);

    let num = 10;
    num();

    const arr=[1,2,3];
    console.log(brr[2])
}

module.exports = runtimeError;